MIDI_DIR = "midi"
DATA_AUG_SOURCE_DIR = MIDI_DIR + "/augSource"
DATA_AUG_OUTPUT_DIR = MIDI_DIR + "/augOutput"
TEST_SOURCE_DIR  = MIDI_DIR + "/test"
TEST_OUTPUT_DIR = TEST_SOURCE_DIR + "/out"
WHOLE_DIR = MIDI_DIR + "/whole"
SPLIT_DIR = MIDI_DIR + "/split"
SEPARATE_DIR = MIDI_DIR + "/separate"
EXAMPLES_DIR = MIDI_DIR + "/examples"

SNA_DIR = EXAMPLES_DIR + "/sna"
KICK_DIR = EXAMPLES_DIR + "/kick"
CYM_DIR = EXAMPLES_DIR + "/cym"
TOM_DIR = EXAMPLES_DIR + "/tom"

KICK_NOTES = [35,36]
SNA_NOTES = [32,34,37,38,39,40]
CYM_NOTES = [33,31,42,44,46,51,52,53,56,57,59]
TOM_NOTES = [41,43,45,47,48,50]

PERC_PARTS = ["kick", "sna", "cym", "tom"]